### ISSUE TITLE
The iot_data_alloc_from_string function in data.c does not handle zero-length string case

### ISSUE THREAD

**Issue by ChristopherEgstad-eaton** [IOTechSystems/iotech-c-utils#216]
- Passing in a zero-length (empty string) into the data.c iot_data_alloc_from_string function is a valid use case. However, the function asserts in this use case, and causes a segfault in our code.
- This function should be re-worked to handle the empty string case, and a test case added for this scenario. In addition a proper NULL check for the 'value' parameter should be added as well. The behavior of the strlen() function is undefined if a NULL pointer passed in, so a NULL check beforehand is imperative.
- I suggest using Coverity or some other static code analysis tool to uncover other issues in this code base. One issue off the bat is the use of unsafe string functions, which will probably result in our internal cybersecurity audit process to flag code from this repo as violating safe coding standards.

**Comment by SteveOss** [comment]
General policy is to assert for "duff" input arguments, rather than have programmatic checks. However for generating a string value an empty value is a valid argument, so will update this function to support passing an empty string. For reference internally we use SonarQube and this repository hits 85% code coverage with zero smells/hotspots/vulnerabilities.

**Comment by SteveOss** [comment]
Fix committed to 1.2 and 1.3 (development) branch. Updated 1.2.5 build released.
